version: '3.7'
services:
  serfit:
    build: .
    volumes:
      - ./app:/app
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
      - 19006:19006
      - 19007:19007
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - CHOKIDAR_USEPOLLING=true

